#!/usr/bin/env sh

target="$1"


if [ "$target" == "prod" ]; then
    set -e
    npm install && npm run build
    php-fpm -D
    nginx -g 'daemon off;'
else
    composer install
    composer update
    npm install && npm run build
    php artisan serve -vvv --ansi --host=0.0.0.0 --port=80
fi


